import {
  Department, Product, Transaction, OnlineOrder,
  StaffTask, StoreActivityItem, SmartMartInsight, StorePulseData, AdminDashboardData
} from '../types';

export const MOCK_DEPARTMENTS: Department[] = [
  { id: 1, name: 'Grocery & Staples', code: 'GROCERY', floor: 'Ground Floor (North)', icon_name: 'wheat', theme_color: '#EBD6DC', description: 'Grains, flours, pulses, edible oils & spices', products_count: 52, staff_count: 8 },
  { id: 2, name: 'Dairy & Chilled', code: 'DAIRY', floor: 'Ground Floor (East)', icon_name: 'milk', theme_color: '#38BDF8', description: 'Fresh milk, butter, cheese, paneer & yogurts', products_count: 36, staff_count: 5 },
  { id: 3, name: 'Beverages & Drinks', code: 'BEVERAGE', floor: 'Ground Floor (West)', icon_name: 'coffee', theme_color: '#F97316', description: 'Juices, energy drinks, teas & coffees', products_count: 42, staff_count: 4 },
  { id: 4, name: 'Snacks & Packaged', code: 'SNACKS', floor: 'Ground Floor (Central)', icon_name: 'cookie', theme_color: '#F59E0B', description: 'Chips, biscuits, namkeen & instant noodles', products_count: 48, staff_count: 6 },
  { id: 5, name: 'Personal Care', code: 'PERSONAL', floor: 'First Floor (Aisle 8)', icon_name: 'sparkles', theme_color: '#EC4899', description: 'Shampoos, soaps, skincare & dental care', products_count: 45, staff_count: 5 },
  { id: 6, name: 'Home Care & Cleaners', code: 'HOMECARE', floor: 'First Floor (Aisle 10)', icon_name: 'sparkle', theme_color: '#10B981', description: 'Detergents, floor cleaners & disinfectants', products_count: 38, staff_count: 4 },
  { id: 7, name: 'Fresh Fruits & Veg', code: 'PRODUCE', floor: 'Ground Floor (Front Entrance)', icon_name: 'apple', theme_color: '#22C55E', description: 'Farm fresh fruits, leafy vegetables & exotics', products_count: 40, staff_count: 7 },
  { id: 8, name: 'Bakery & Confectionery', code: 'BAKERY', floor: 'Ground Floor (Corner)', icon_name: 'cake', theme_color: '#D97706', description: 'Artisan bread, buns, cakes & cookies', products_count: 28, staff_count: 4 },
];

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 1,
    sku: 'SKU-AMUL-GOLD',
    barcode: '8901262010053',
    name: 'Amul Gold Homogenised Standardised Milk',
    brand: 'Amul',
    department: 2,
    department_name: 'Dairy & Chilled',
    department_code: 'DAIRY',
    department_color: '#38BDF8',
    aisle_number: 2,
    aisle_name: 'Aisle 2 - Chilled Dairy Wall',
    shelf_code: 'D-02',
    price: 33,
    mrp: 35,
    discount_percent: 6,
    stock: 145,
    min_stock: 30,
    stock_status: 'HEALTHY',
    unit: '500 ml Pouch',
    image_url: 'https://images.unsplash.com/photo-1550583724-b2692b85b150?w=500',
    description: 'Pasteurized standard milk packed with vital nutrients and calcium.',
    rating: 4.8,
    is_featured: true,
    is_bestseller: true,
    is_active: true,
  },
  {
    id: 2,
    sku: 'SKU-AASH-ATTA',
    barcode: '8901030383452',
    name: 'Aashirvaad Shudh Chakki Whole Wheat Atta',
    brand: 'Aashirvaad',
    department: 1,
    department_name: 'Grocery & Staples',
    department_code: 'GROCERY',
    department_color: '#EBD6DC',
    aisle_number: 1,
    aisle_name: 'Aisle 1 - Flours & Grains',
    shelf_code: 'A-01',
    price: 245,
    mrp: 295,
    discount_percent: 17,
    stock: 82,
    min_stock: 20,
    stock_status: 'HEALTHY',
    unit: '5 kg Pack',
    image_url: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=500',
    description: '100% whole wheat flour made with traditional stone-ground chakki process.',
    rating: 4.9,
    is_featured: true,
    is_bestseller: true,
    is_active: true,
  },
  {
    id: 3,
    sku: 'SKU-TATA-SALT',
    barcode: '8901030000014',
    name: 'Tata Salt Vacuum Evaporated Iodised Salt',
    brand: 'Tata Consumer',
    department: 1,
    department_name: 'Grocery & Staples',
    department_code: 'GROCERY',
    department_color: '#EBD6DC',
    aisle_number: 1,
    aisle_name: 'Aisle 1 - Spices & Seasoning',
    shelf_code: 'A-04',
    price: 26,
    mrp: 28,
    discount_percent: 7,
    stock: 210,
    min_stock: 50,
    stock_status: 'HEALTHY',
    unit: '1 kg Pouch',
    image_url: 'https://images.unsplash.com/photo-1518110925495-5fe2fda0442c?w=500',
    description: 'India’s pioneer vacuum evaporated iodised salt for balanced thyroid health.',
    rating: 4.9,
    is_featured: false,
    is_bestseller: true,
    is_active: true,
  },
  {
    id: 4,
    sku: 'SKU-SURF-EXCEL',
    barcode: '8901030825310',
    name: 'Surf Excel Easy Wash Detergent Powder',
    brand: 'Surf Excel',
    department: 6,
    department_name: 'Home Care & Cleaners',
    department_code: 'HOMECARE',
    department_color: '#10B981',
    aisle_number: 10,
    aisle_name: 'Aisle 10 - Laundry & Detergents',
    shelf_code: 'J-03',
    price: 135,
    mrp: 160,
    discount_percent: 16,
    stock: 64,
    min_stock: 15,
    stock_status: 'HEALTHY',
    unit: '1 kg Poly Pack',
    image_url: 'https://images.unsplash.com/photo-1610557892470-55d9e80c0bce?w=500',
    description: 'Advanced formula lifts tough stains like mud, grease, and ink effortlessly.',
    rating: 4.7,
    is_featured: true,
    is_bestseller: true,
    is_active: true,
  },
  {
    id: 5,
    sku: 'SKU-DOVE-SHAMP',
    barcode: '8901030704981',
    name: 'Dove Intense Repair Shampoo with Keratin Actives',
    brand: 'Dove',
    department: 5,
    department_name: 'Personal Care',
    department_code: 'PERSONAL',
    department_color: '#EC4899',
    aisle_number: 8,
    aisle_name: 'Aisle 8 - Hair Care & Spa',
    shelf_code: 'H-02',
    price: 380,
    mrp: 450,
    discount_percent: 15,
    stock: 42,
    min_stock: 15,
    stock_status: 'HEALTHY',
    unit: '650 ml Pump Bottle',
    image_url: 'https://images.unsplash.com/photo-1535585209827-a15fcdbc4c2d?w=500',
    description: 'Enriched with Keratin Actives that nourish damaged and brittle hair.',
    rating: 4.8,
    is_featured: true,
    is_bestseller: false,
    is_active: true,
  },
  {
    id: 6,
    sku: 'SKU-MAGGI-MASALA',
    barcode: '8901058852372',
    name: 'Maggi 2-Minute Masala Instant Noodles 4-Pack',
    brand: 'Nestle Maggi',
    department: 4,
    department_name: 'Snacks & Packaged',
    department_code: 'SNACKS',
    department_color: '#F59E0B',
    aisle_number: 4,
    aisle_name: 'Aisle 4 - Instant Food & Soups',
    shelf_code: 'C-01',
    price: 56,
    mrp: 60,
    discount_percent: 7,
    stock: 180,
    min_stock: 40,
    stock_status: 'HEALTHY',
    unit: '280 g (4 x 70g)',
    image_url: 'https://images.unsplash.com/photo-1612927601601-6638404737ce?w=500',
    description: 'Favorite instant noodles with authentic roasted Indian spices aroma.',
    rating: 4.9,
    is_featured: true,
    is_bestseller: true,
    is_active: true,
  },
  {
    id: 7,
    sku: 'SKU-INDIA-GATE',
    barcode: '8901537001021',
    name: 'India Gate Feast Rozzana Premium Basmati Rice',
    brand: 'India Gate',
    department: 1,
    department_name: 'Grocery & Staples',
    department_code: 'GROCERY',
    department_color: '#EBD6DC',
    aisle_number: 1,
    aisle_name: 'Aisle 1 - Premium Rices',
    shelf_code: 'A-02',
    price: 395,
    mrp: 475,
    discount_percent: 17,
    stock: 58,
    min_stock: 20,
    stock_status: 'HEALTHY',
    unit: '5 kg Bag',
    image_url: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=500',
    description: 'Aged long-grain Basmati rice known for delicate aroma and fluffy texture.',
    rating: 4.7,
    is_featured: true,
    is_bestseller: true,
    is_active: true,
  },
  {
    id: 8,
    sku: 'SKU-FORTUNE-OIL',
    barcode: '8906007281014',
    name: 'Fortune Sunlite Refined Sunflower Oil',
    brand: 'Fortune',
    department: 1,
    department_name: 'Grocery & Staples',
    department_code: 'GROCERY',
    department_color: '#EBD6DC',
    aisle_number: 1,
    aisle_name: 'Aisle 1 - Edible Oils',
    shelf_code: 'A-05',
    price: 142,
    mrp: 170,
    discount_percent: 16,
    stock: 12,
    min_stock: 25,
    stock_status: 'LOW_STOCK',
    unit: '1 Litre Pouch',
    image_url: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=500',
    description: 'Light and non-greasy sunflower cooking oil fortified with Vitamins A & D.',
    rating: 4.6,
    is_featured: false,
    is_bestseller: true,
    is_active: true,
  },
  {
    id: 9,
    sku: 'SKU-AMUL-BUTTER',
    barcode: '8901262010107',
    name: 'Amul Pasteurised Salted Butter 500g',
    brand: 'Amul',
    department: 2,
    department_name: 'Dairy & Chilled',
    department_code: 'DAIRY',
    department_color: '#38BDF8',
    aisle_number: 2,
    aisle_name: 'Aisle 2 - Dairy & Chilled Wall',
    shelf_code: 'D-03',
    price: 275,
    mrp: 285,
    discount_percent: 4,
    stock: 95,
    min_stock: 20,
    stock_status: 'HEALTHY',
    unit: '500 g Carton',
    image_url: 'https://images.unsplash.com/photo-1589985270826-4b7bb135bc9d?w=500',
    description: 'Classic creamy butter made from pure fresh cream.',
    rating: 4.9,
    is_featured: true,
    is_bestseller: true,
    is_active: true,
  },
  {
    id: 10,
    sku: 'SKU-AMUL-PANEER',
    barcode: '8901262010213',
    name: 'Amul Fresh Malai Paneer 200g',
    brand: 'Amul',
    department: 2,
    department_name: 'Dairy & Chilled',
    department_code: 'DAIRY',
    department_color: '#38BDF8',
    aisle_number: 2,
    aisle_name: 'Aisle 2 - Dairy & Chilled Wall',
    shelf_code: 'D-04',
    price: 92,
    mrp: 98,
    discount_percent: 6,
    stock: 60,
    min_stock: 15,
    stock_status: 'HEALTHY',
    unit: '200 g Pack',
    image_url: 'https://images.unsplash.com/photo-1589985270826-4b7bb135bc9d?w=500',
    description: 'Soft and delicious block of fresh cottage cheese.',
    rating: 4.8,
    is_featured: false,
    is_bestseller: true,
    is_active: true,
  },
  {
    id: 11,
    sku: 'SKU-TATA-TEA',
    barcode: '8901030005019',
    name: 'Tata Tea Gold Leaf & Dust Blend 500g',
    brand: 'Tata Consumer',
    department: 3,
    department_name: 'Beverages & Drinks',
    department_code: 'BEVERAGE',
    department_color: '#F97316',
    aisle_number: 3,
    aisle_name: 'Aisle 3 - Hot Beverages',
    shelf_code: 'B-01',
    price: 315,
    mrp: 360,
    discount_percent: 13,
    stock: 75,
    min_stock: 20,
    stock_status: 'HEALTHY',
    unit: '500 g Pack',
    image_url: 'https://images.unsplash.com/photo-1544787219-7f47ccb76574?w=500',
    description: 'Exquisite blend of CTC tea granules and gently rolled long tea leaves.',
    rating: 4.8,
    is_featured: true,
    is_bestseller: true,
    is_active: true,
  },
  {
    id: 12,
    sku: 'SKU-NESCAFE-CLAS',
    barcode: '8901058000100',
    name: 'Nescafé Classic 100% Pure Instant Coffee 200g Jar',
    brand: 'Nestle',
    department: 3,
    department_name: 'Beverages & Drinks',
    department_code: 'BEVERAGE',
    department_color: '#F97316',
    aisle_number: 3,
    aisle_name: 'Aisle 3 - Hot Beverages',
    shelf_code: 'B-02',
    price: 575,
    mrp: 620,
    discount_percent: 7,
    stock: 45,
    min_stock: 12,
    stock_status: 'HEALTHY',
    unit: '200 g Glass Jar',
    image_url: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=500',
    description: 'Rich aroma and bold taste roasted to perfection.',
    rating: 4.9,
    is_featured: true,
    is_bestseller: true,
    is_active: true,
  },
  {
    id: 13,
    sku: 'SKU-COCA-COLA',
    barcode: '8901764012204',
    name: 'Coca-Cola Original Soft Drink 750ml Bottle',
    brand: 'Coca-Cola',
    department: 3,
    department_name: 'Beverages & Drinks',
    department_code: 'BEVERAGE',
    department_color: '#F97316',
    aisle_number: 3,
    aisle_name: 'Aisle 3 - Cold Drinks & Juices',
    shelf_code: 'B-05',
    price: 40,
    mrp: 45,
    discount_percent: 11,
    stock: 120,
    min_stock: 30,
    stock_status: 'HEALTHY',
    unit: '750 ml Pet Bottle',
    image_url: 'https://images.unsplash.com/photo-1622483767028-3f66f32aef97?w=500',
    description: 'Iconic refreshing carbonated soft drink.',
    rating: 4.7,
    is_featured: false,
    is_bestseller: true,
    is_active: true,
  },
  {
    id: 14,
    sku: 'SKU-BRIT-BREAD',
    barcode: '8901063012013',
    name: 'Britannia 100% Whole Wheat Bread 400g',
    brand: 'Britannia',
    department: 8,
    department_name: 'Bakery & Confectionery',
    department_code: 'BAKERY',
    department_color: '#D97706',
    aisle_number: 7,
    aisle_name: 'Aisle 7 - Fresh Bakery & Buns',
    shelf_code: 'K-01',
    price: 50,
    mrp: 55,
    discount_percent: 9,
    stock: 40,
    min_stock: 15,
    stock_status: 'HEALTHY',
    unit: '400 g Loaf',
    image_url: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=500',
    description: 'Healthy and wholesome brown wheat bread baked fresh daily.',
    rating: 4.8,
    is_featured: true,
    is_bestseller: true,
    is_active: true,
  },
  {
    id: 15,
    sku: 'SKU-HALD-BHUJIA',
    barcode: '8904063200018',
    name: 'Haldiram’s Nagpur Sev Bhujia Namkeen 400g',
    brand: 'Haldirams',
    department: 4,
    department_name: 'Snacks & Packaged',
    department_code: 'SNACKS',
    department_color: '#F59E0B',
    aisle_number: 4,
    aisle_name: 'Aisle 4 - Indian Namkeens',
    shelf_code: 'C-03',
    price: 110,
    mrp: 125,
    discount_percent: 12,
    stock: 85,
    min_stock: 25,
    stock_status: 'HEALTHY',
    unit: '400 g Pouch',
    image_url: 'https://images.unsplash.com/photo-1566478989037-eec170784d0b?w=500',
    description: 'Crisp and spicy classic Indian tepary bean and chickpea snack.',
    rating: 4.9,
    is_featured: true,
    is_bestseller: true,
    is_active: true,
  },
  {
    id: 16,
    sku: 'SKU-LAYS-MAGIC',
    barcode: '8901491101831',
    name: 'Lay’s India’s Magic Masala Potato Chips 90g',
    brand: 'Lays',
    department: 4,
    department_name: 'Snacks & Packaged',
    department_code: 'SNACKS',
    department_color: '#F59E0B',
    aisle_number: 4,
    aisle_name: 'Aisle 4 - Crisps & Chips',
    shelf_code: 'C-04',
    price: 38,
    mrp: 40,
    discount_percent: 5,
    stock: 140,
    min_stock: 35,
    stock_status: 'HEALTHY',
    unit: '90g Bag',
    image_url: 'https://images.unsplash.com/photo-1566478989037-eec170784d0b?w=500',
    description: 'Crispy sliced potatoes spiced with an aromatic mix of Indian herbs and spices.',
    rating: 4.7,
    is_featured: false,
    is_bestseller: true,
    is_active: true,
  },
  {
    id: 17,
    sku: 'SKU-COLGATE-MAX',
    barcode: '8901314010502',
    name: 'Colgate MaxFresh Spicy Red Cooling Crystals Toothpaste 150g',
    brand: 'Colgate',
    department: 5,
    department_name: 'Personal Care',
    department_code: 'PERSONAL',
    department_color: '#EC4899',
    aisle_number: 8,
    aisle_name: 'Aisle 8 - Dental Care',
    shelf_code: 'H-04',
    price: 125,
    mrp: 145,
    discount_percent: 14,
    stock: 55,
    min_stock: 18,
    stock_status: 'HEALTHY',
    unit: '150 g Tube',
    image_url: 'https://images.unsplash.com/photo-1559591937-e1104e76a61b?w=500',
    description: 'Infused with cooling crystals that give an intense explosion of freshness.',
    rating: 4.7,
    is_featured: false,
    is_bestseller: true,
    is_active: true,
  },
  {
    id: 18,
    sku: 'SKU-DETTOL-ORIG',
    barcode: '8901396010014',
    name: 'Dettol Original Germ Protection Bathing Soap (Pack of 4x125g)',
    brand: 'Dettol',
    department: 5,
    department_name: 'Personal Care',
    department_code: 'PERSONAL',
    department_color: '#EC4899',
    aisle_number: 8,
    aisle_name: 'Aisle 8 - Soaps & Body Wash',
    shelf_code: 'H-01',
    price: 195,
    mrp: 230,
    discount_percent: 15,
    stock: 70,
    min_stock: 20,
    stock_status: 'HEALTHY',
    unit: 'Pack of 4 (500g)',
    image_url: 'https://images.unsplash.com/photo-1607006483224-4f81498b3f27?w=500',
    description: 'Trusted germ protection with pine fragrance for everyday family hygiene.',
    rating: 4.8,
    is_featured: true,
    is_bestseller: true,
    is_active: true,
  },
  {
    id: 19,
    sku: 'SKU-HARPIC-POWER',
    barcode: '8901396340050',
    name: 'Harpic Power Plus 10X Max Disinfectant Toilet Cleaner 1L',
    brand: 'Harpic',
    department: 6,
    department_name: 'Home Care & Cleaners',
    department_code: 'HOMECARE',
    department_color: '#10B981',
    aisle_number: 10,
    aisle_name: 'Aisle 10 - Surface Disinfectants',
    shelf_code: 'J-01',
    price: 198,
    mrp: 230,
    discount_percent: 14,
    stock: 48,
    min_stock: 15,
    stock_status: 'HEALTHY',
    unit: '1 Litre Bottle',
    image_url: 'https://images.unsplash.com/photo-1584820927498-cfe5211fd8bf?w=500',
    description: '10x better stain removal, kills 99.9% germs leaving toilet spotless.',
    rating: 4.8,
    is_featured: false,
    is_bestseller: true,
    is_active: true,
  },
  {
    id: 20,
    sku: 'SKU-VIM-LIQUID',
    barcode: '8901030612019',
    name: 'Vim Dishwash Gel with Real Lemon Power 750ml Bottle',
    brand: 'Vim',
    department: 6,
    department_name: 'Home Care & Cleaners',
    department_code: 'HOMECARE',
    department_color: '#10B981',
    aisle_number: 10,
    aisle_name: 'Aisle 10 - Kitchen Cleaners',
    shelf_code: 'J-05',
    price: 155,
    mrp: 180,
    discount_percent: 14,
    stock: 62,
    min_stock: 20,
    stock_status: 'HEALTHY',
    unit: '750 ml Bottle',
    image_url: 'https://images.unsplash.com/photo-1585670210693-e7fdd16b142e?w=500',
    description: 'Just 1 spoon of Vim gel removes tough grease from greasy utensils easily.',
    rating: 4.8,
    is_featured: true,
    is_bestseller: true,
    is_active: true,
  },
  {
    id: 21,
    sku: 'SKU-FARM-ONION',
    barcode: '8900000000011',
    name: 'Farm Fresh Red Onions 1kg',
    brand: 'Fresh Produce',
    department: 7,
    department_name: 'Fresh Fruits & Veg',
    department_code: 'PRODUCE',
    department_color: '#22C55E',
    aisle_number: 11,
    aisle_name: 'Aisle 11 - Vegetables & Root Crops',
    shelf_code: 'V-01',
    price: 38,
    mrp: 45,
    discount_percent: 15,
    stock: 350,
    min_stock: 50,
    stock_status: 'HEALTHY',
    unit: '1 kg Net',
    image_url: 'https://images.unsplash.com/photo-1580201092675-a0a6a6cafbb1?w=500',
    description: 'Handpicked crisp red onions from local farms.',
    rating: 4.6,
    is_featured: false,
    is_bestseller: true,
    is_active: true,
  },
  {
    id: 22,
    sku: 'SKU-FARM-POTATO',
    barcode: '8900000000028',
    name: 'Farm Fresh Jyoti Potatoes 1kg',
    brand: 'Fresh Produce',
    department: 7,
    department_name: 'Fresh Fruits & Veg',
    department_code: 'PRODUCE',
    department_color: '#22C55E',
    aisle_number: 11,
    aisle_name: 'Aisle 11 - Vegetables & Root Crops',
    shelf_code: 'V-02',
    price: 28,
    mrp: 35,
    discount_percent: 20,
    stock: 420,
    min_stock: 60,
    stock_status: 'HEALTHY',
    unit: '1 kg Net',
    image_url: 'https://images.unsplash.com/photo-1518977676601-b53f82aba655?w=500',
    description: 'Cleaned, firm, high-grade daily cooking potatoes.',
    rating: 4.7,
    is_featured: false,
    is_bestseller: true,
    is_active: true,
  },
  {
    id: 23,
    sku: 'SKU-ROYAL-GALA',
    barcode: '8900000000035',
    name: 'Crisp Shimla Royal Gala Apples 4-Pack (approx 650g)',
    brand: 'Fresh Produce',
    department: 7,
    department_name: 'Fresh Fruits & Veg',
    department_code: 'PRODUCE',
    department_color: '#22C55E',
    aisle_number: 12,
    aisle_name: 'Aisle 12 - Premium Fresh Fruits',
    shelf_code: 'V-08',
    price: 140,
    mrp: 170,
    discount_percent: 18,
    stock: 80,
    min_stock: 20,
    stock_status: 'HEALTHY',
    unit: 'Pack of 4',
    image_url: 'https://images.unsplash.com/photo-1560806887-1e4cd0b6cbd6?w=500',
    description: 'Sweet, juicy, and crunchy mountain apples.',
    rating: 4.9,
    is_featured: true,
    is_bestseller: true,
    is_active: true,
  },
  {
    id: 24,
    sku: 'SKU-PARLE-G',
    barcode: '8901719101015',
    name: 'Parle-G Original Gluco Biscuits 800g Value Pack',
    brand: 'Parle',
    department: 4,
    department_name: 'Snacks & Packaged',
    department_code: 'SNACKS',
    department_color: '#F59E0B',
    aisle_number: 4,
    aisle_name: 'Aisle 4 - Biscuits & Cookies',
    shelf_code: 'C-02',
    price: 75,
    mrp: 85,
    discount_percent: 12,
    stock: 160,
    min_stock: 40,
    stock_status: 'HEALTHY',
    unit: '800 g Pack',
    image_url: 'https://images.unsplash.com/photo-1558961363-fa8fdf82db35?w=500',
    description: 'India’s favorite glucose biscuit rich in wheat and milk nourishment.',
    rating: 4.9,
    is_featured: false,
    is_bestseller: true,
    is_active: true,
  },
];

export const MOCK_TRANSACTIONS: Transaction[] = [
  {
    id: 101,
    invoice_number: 'INV-2026-0918',
    customer_phone: '+91 98765 43210',
    customer_name: 'Pooja Verma',
    subtotal: 574,
    tax_amount: 28,
    discount_amount: 50,
    total: 552,
    payment_mode: 'UPI',
    status: 'PAID',
    cashier_id: 1,
    cashier_name: 'Vikram Singhania (Lane 3)',
    created_at: new Date(Date.now() - 3600000).toISOString(),
    items: [
      { id: 1, product_name: 'Aashirvaad Shudh Chakki Atta', product_barcode: '8901030383452', product_unit: '5 kg', quantity: 1, unit_price: 245, subtotal: 245 },
      { id: 2, product_name: 'Surf Excel Easy Wash Detergent', product_barcode: '8901030825310', product_unit: '1 kg', quantity: 2, unit_price: 135, subtotal: 270 },
      { id: 3, product_name: 'Maggi 2-Minute Masala Noodles', product_barcode: '8901058852372', product_unit: '4-Pack', quantity: 1, unit_price: 56, subtotal: 56 },
    ],
  },
  {
    id: 102,
    invoice_number: 'INV-2026-0915',
    customer_phone: '+91 98765 43210',
    customer_name: 'Pooja Verma',
    subtotal: 775,
    tax_amount: 38,
    discount_amount: 0,
    total: 813,
    payment_mode: 'CARD',
    status: 'PAID',
    cashier_id: 2,
    cashier_name: 'Priya Patel (Lane 1)',
    created_at: new Date(Date.now() - 86400000 * 2).toISOString(),
    items: [
      { id: 4, product_name: 'India Gate Feast Rozzana Basmati', product_barcode: '8901537001021', product_unit: '5 kg', quantity: 1, unit_price: 395, subtotal: 395 },
      { id: 5, product_name: 'Dove Intense Repair Shampoo', product_barcode: '8901030704981', product_unit: '650 ml', quantity: 1, unit_price: 380, subtotal: 380 },
    ],
  },
];

export const MOCK_ORDERS: OnlineOrder[] = [
  {
    id: 201,
    order_number: 'ORD-2026-4821',
    status: 'CONFIRMED',
    delivery_address: 'Flat 402, Green Glen Heights, Bellandur, Bengaluru - 560103',
    delivery_slot: 'Today, 2-Hour Express Delivery',
    subtotal: 673,
    delivery_fee: 0,
    discount: 50,
    total: 623,
    payment_method: 'UPI (PhonePe)',
    payment_status: 'PAID',
    created_at: new Date(Date.now() - 1800000).toISOString(),
    estimated_delivery: 'Arriving in 35 mins',
    items: [
      { id: 1, product_name: 'Amul Gold Milk', product_unit: '500 ml', quantity: 3, unit_price: 33, subtotal: 99 },
      { id: 2, product_name: 'India Gate Basmati Rice', product_unit: '5 kg', quantity: 1, unit_price: 395, subtotal: 395 },
      { id: 3, product_name: 'Fortune Sunlite Refined Oil', product_unit: '1 L', quantity: 1, unit_price: 142, subtotal: 142 },
    ],
  },
];

export const MOCK_STAFF_TASKS: StaffTask[] = [
  {
    id: 301,
    title: 'Restock Aisle 1 - Edible Oils',
    description: 'Fortune Sunflower Oil is low on shelf A-05. Transfer 30 units from Warehouse Bay B4.',
    department_name: 'Grocery & Staples',
    priority: 'CRITICAL',
    status: 'PENDING',
    due_time: '12:00 PM Today',
    assigned_to_name: 'Rahul Sharma',
  },
  {
    id: 302,
    title: 'Audit Chilled Dairy Expiry Dates',
    description: 'Verify shelf life and FIFO rotation across butter, curd, and milk pouches.',
    department_name: 'Dairy & Chilled',
    priority: 'HIGH',
    status: 'IN_PROGRESS',
    due_time: '02:30 PM Today',
    assigned_to_name: 'Rahul Sharma',
  },
  {
    id: 303,
    title: 'Set up Weekend Promo Banners',
    description: 'Place 15% OFF floor standees at entrance and Aisle 8 Personal Care corner.',
    department_name: 'Floor Operations',
    priority: 'MEDIUM',
    status: 'COMPLETED',
    due_time: '10:00 AM Today',
    assigned_to_name: 'Rahul Sharma',
  },
];

export const MOCK_SUPPLIERS = [
  { id: 1, name: 'Amul Gujarat Co-op Milk Federation', category: 'Dairy & Chilled', contact_person: 'Ramesh Patel', phone: '+91 98250 12345', email: 'supply@amul.coop', lead_time_days: 1 },
  { id: 2, name: 'ITC Limited FMCG Division', category: 'Grocery & Staples', contact_person: 'Siddharth Sen', phone: '+91 98300 54321', email: 'orders@itc.in', lead_time_days: 2 },
  { id: 3, name: 'Hindustan Unilever Limited (HUL)', category: 'Personal & Home Care', contact_person: 'Anita Nair', phone: '+91 98200 98765', email: 'sales@hul.com', lead_time_days: 2 },
  { id: 4, name: 'Nestlé India Logistics', category: 'Snacks & Packaged Food', contact_person: 'Manish Rawat', phone: '+91 98110 33445', email: 'distrib@nestle.in', lead_time_days: 3 },
];

export const MOCK_PURCHASE_ORDERS = [
  { id: 401, po_number: 'PO-2026-8801', supplier_name: 'Amul Gujarat Co-op', total_amount: '48,500.00', status: 'RECEIVED', created_at: '2026-09-17T10:00:00Z', items_count: 6 },
  { id: 402, po_number: 'PO-2026-8802', supplier_name: 'ITC Limited FMCG', total_amount: '94,200.00', status: 'PENDING', created_at: '2026-09-18T14:30:00Z', items_count: 12 },
  { id: 403, po_number: 'PO-2026-8803', supplier_name: 'Hindustan Unilever', total_amount: '62,800.00', status: 'PENDING', created_at: '2026-09-19T09:15:00Z', items_count: 9 },
];

export const MOCK_ADMIN_DASHBOARD: AdminDashboardData = {
  kpis: {
    today_revenue_formatted: '₹8.42L',
    customers_count: 1020,
    transactions_count: 1050,
    online_orders_count: 520,
    inventory_health: '94%',
    low_stock_count: 18,
    staff_present: 47,
    open_tasks_count: 7,
  },
  department_sales: [
    { department_name: 'Grocery & Staples', revenue: 286000, percentage: 34 },
    { department_name: 'Dairy & Chilled', revenue: 168000, percentage: 20 },
    { department_name: 'Snacks & Packaged', revenue: 134000, percentage: 16 },
    { department_name: 'Personal Care', revenue: 126000, percentage: 15 },
    { department_name: 'Home Care', revenue: 84000, percentage: 10 },
    { department_name: 'Others', revenue: 44000, percentage: 5 },
  ],
};

export const MOCK_STORE_PULSE: StorePulseData = {
  footfall_percent: 78,
  sales_velocity_percent: 89,
  inventory_sync_percent: 94,
  active_lanes: '8 of 8 Open',
  current_occupancy: 184,
  max_occupancy: 250,
  last_sync: 'Just now',
};

export const MOCK_INSIGHTS: SmartMartInsight[] = [
  {
    id: 'ins-1',
    type: 'ALERT',
    title: '18 Low-Stock SKUs Detected',
    message: 'Edible oils & dairy replenishment needed before weekend peak rush.',
    action_label: 'Review Restock Queue',
    action_target: 'inventory',
  },
  {
    id: 'ins-2',
    type: 'TREND',
    title: 'Grocery Sales Up +24% Today',
    message: 'Aashirvaad Atta and India Gate Rice top grossing items this morning.',
    action_label: 'View Department Breakdown',
    action_target: 'reports',
  },
  {
    id: 'ins-3',
    type: 'OPTIMIZATION',
    title: 'Cashier Lane 3 Velocity: 1.6m/cart',
    message: 'Lane 3 is processing checkouts 15% faster than store average.',
    action_label: 'Inspect POS Registers',
    action_target: 'pos',
  },
];

export const MOCK_ACTIVITIES: StoreActivityItem[] = [
  { id: 'act-1', text: 'POS Bill #INV-2026-0918 generated by Lane 3 (₹552)', timestamp: '2m ago', type: 'POS' },
  { id: 'act-2', text: 'Online Express Order #ORD-2026-4821 confirmed', timestamp: '5m ago', type: 'ORDER' },
  { id: 'act-3', text: 'Rahul Sharma clocked IN at Store Gate 1 (GPS Verified)', timestamp: '14m ago', type: 'STAFF' },
  { id: 'act-4', text: 'Stock replenished: 50 units of Surf Excel added', timestamp: '28m ago', type: 'INVENTORY' },
];

export const MOCK_NOTIFICATIONS = [
  { id: 1, title: '🔔 Bill Generated at Counter', message: 'Your in-store bill for ₹552 is ready for digital checkout.', is_read: false, created_at: '2m ago' },
  { id: 2, title: '🚚 Express Delivery En Route', message: 'Order #ORD-2026-4821 is picked and out for delivery.', is_read: false, created_at: '10m ago' },
  { id: 3, title: '🏷️ Flash Supermarket Offer', message: 'Get 15% off across all Whole Wheat Attas today.', is_read: true, created_at: '1h ago' },
];
